VMS homework/Controllers/OppTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VMS_homework.Models;

namespace VMS_homework.Controllers
{
    public class OppTablesController : Controller
    {
        private OpportunityEntities db = new OpportunityEntities();

        // GET: OppTables
        [Authorize]
        public ActionResult Index()
        {
            return View(db.OppTables.ToList());
        }

        // GET: OppTables/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OppTable oppTable = db.OppTables.Find(id);
            if (oppTable == null)
            {
                return HttpNotFound();
            }
            return View(oppTable);
        }

        // GET: OppTables/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: OppTables/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "Id,Opportunity,OpportunityStartDate,OpportunityStopDate,OpportunityLastComp,OpportunityCenter")] OppTable oppTable)
        {
            if (ModelState.IsValid)
            {
                db.OppTables.Add(oppTable);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(oppTable);
        }

        // GET: OppTables/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OppTable oppTable = db.OppTables.Find(id);
            if (oppTable == null)
            {
                return HttpNotFound();
            }
            return View(oppTable);
        }

        // POST: OppTables/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "Id,Opportunity,OpportunityStartDate,OpportunityStopDate,OpportunityLastComp,OpportunityCenter")] OppTable oppTable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(oppTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(oppTable);
        }

        // GET: OppTables/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OppTable oppTable = db.OppTables.Find(id);
            if (oppTable == null)
            {
                return HttpNotFound();
            }
            return View(oppTable);
        }

        // POST: OppTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            OppTable oppTable = db.OppTables.Find(id);
            db.OppTables.Remove(oppTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult ManageOpp()
        {
            return View(db.OppTables.ToList());
        }

        [Authorize]
        public ActionResult ChangeFilter()
        {
            return View();
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VMS homework/Controllers/SearchOppController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VMS_homework.Models;

namespace VMS_homework.Controllers
{
    public class SearchOppController : Controller
    {
        OpportunityEntities db = new OpportunityEntities();
        // GET: Search

        //Lets the administrator search for Opportunity by name
        [Authorize]
        public ActionResult Index(String searching)
        {
            var status = from s in db.OppTables
                         select s;
            if (!String.IsNullOrEmpty(searching))
            {
                status = status.Where(s => s.Opportunity.Contains(searching));
            }
            return View(status.ToList());

        }

        //returns all Opportunities in last 60 days
        [Authorize]
        public ActionResult MostRecent()
        {
            var status = from s in db.OppTables
                         select s;
            
            DateTime time = DateTime.Today.AddDays(-60);
            status = status.Where(s => (s.OpportunityStartDate.CompareTo(time)) >= 0);

            return View(status.ToList());
        }

        //Lets the administrator search for Opportunity by Center
        [Authorize]
        public ActionResult ByCenter(String searching)
        {
            var status = from s in db.OppTables
                         select s;
            if (!String.IsNullOrEmpty(searching))
            {
                status = status.Where(s => s.OpportunityCenter.Contains(searching));
            }
            return View(status.ToList());
        }
    }
}

VMS homework/Views/OppTables/ChangeFilter.cshtml
@{
    ViewBag.Title = "ChangeFilter";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Change Filter</h2>
<div>
    @Html.ActionLink("a.	a.	Most Recent (60 days)", "Mostrecent", "SearchOpp")
</div>
<div>
    @Html.ActionLink("b.	b.	By Center", "ByCenter", "SearchOpp")
</div>

VMS homework/Views/OppTables/Create.cshtml
@model VMS_homework.Models.OppTable

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OppTable</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Opportunity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Opportunity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Opportunity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OpportunityStartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OpportunityStartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OpportunityStartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OpportunityStopDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OpportunityStopDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OpportunityStopDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OpportunityLastComp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OpportunityLastComp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OpportunityLastComp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OpportunityCenter, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OpportunityCenter, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OpportunityCenter, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VMS homework/Views/OppTables/Delete.cshtml
@model VMS_homework.Models.OppTable

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OppTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Opportunity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opportunity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpportunityStartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpportunityStartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpportunityStopDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpportunityStopDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpportunityLastComp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpportunityLastComp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpportunityCenter)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpportunityCenter)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

VMS homework/Views/OppTables/Details.cshtml
@model VMS_homework.Models.OppTable

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>OppTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Opportunity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opportunity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpportunityStartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpportunityStartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpportunityStopDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpportunityStopDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpportunityLastComp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpportunityLastComp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpportunityCenter)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpportunityCenter)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

VMS homework/Views/OppTables/Edit.cshtml
@model VMS_homework.Models.OppTable

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OppTable</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Opportunity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Opportunity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Opportunity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OpportunityStartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OpportunityStartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OpportunityStartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OpportunityStopDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OpportunityStopDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OpportunityStopDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OpportunityLastComp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OpportunityLastComp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OpportunityLastComp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OpportunityCenter, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OpportunityCenter, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OpportunityCenter, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VMS homework/Views/OppTables/Index.cshtml
@model IEnumerable<VMS_homework.Models.OppTable>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Opportunity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OpportunityStartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OpportunityStopDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OpportunityLastComp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OpportunityCenter)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Opportunity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OpportunityStartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OpportunityStopDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OpportunityLastComp)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OpportunityCenter)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

VMS homework/Views/OppTables/ManageOpp.cshtml
@model IEnumerable<VMS_homework.Models.OppTable>

@{
    ViewBag.Title = "ManageOpp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ManageOpp</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Opportunity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OpportunityCenter)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OpportunityLastComp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OpportunityStartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OpportunityStartDate)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Opportunity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OpportunityCenter)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OpportunityLastComp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OpportunityStartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OpportunityStopDate)
            </td>
        </tr>
    }
</table>
<div>
    @Html.ActionLink("a.	Change Opportunity Filter", "ChangeFilter", "OppTables")
</div>
<div>
    @Html.ActionLink("b.	Search Opportunity", "Index", "SearchOpp")
</div>
<p>c.	View Volunteer Opportunity Matches</p>
<div>
    @Html.ActionLink("d.	Edit Opportunity", "Index", "SearchOpp")
</div>
<div>
@Html.ActionLink("e.	Add New Opportunity", "Create", "OppTables")
</div>
@Html.ActionLink("e.	Delete Opportunity", "Index", "OppTables")